---
title: "R Notebook"
output: html_notebook
---

```{r}
library("e1071")
library(plotly)
library(data.table)
load("armdata.RData")
head(armdata[[2]][[1]][[1]])
# e2 = lapply(armdata[[2]][], data.frame)
# array(data = NA,dim = c(10,10,100,3))

```
**Getting coeffecients "fingerprint" of trajectory**
```{r}
Names = list(c("person1","person2","person3","person4","person5","person6","person7","person8","person9","person10"),
             c("repetition1","repetition2","repetition3","repetition4","repetition5","repetition6","repetition7","repetition8","repetition9","repetition10"),
             c("coef1","coef2","coef3","coef4","coef5","coef6","coef7","coef8","coef9","coef10"))
             

data <- array(data = NA,
              dim = c(10,10,10),
              dimnames = Names)

for (i in 1:10){ # 10 persons
  for (j in 1:10){ # 10 repetitions
    model = lm(armdata[[2]][[i]][[j]][,1] ~ poly(armdata[[2]][[i]][[j]][,2],armdata[[2]][[i]][[j]][,3], degree = 3 ))
    
    data[i,j,] = unname(coef(model))
    
    
  } 
# print(mean(data[i,j,]))
}
test = unname(coef(model))


arr = as.data.frame(data, )
```


```{r}
p = 1 # person to plot
c = 6 # coef to plot

for (i in 1:10){
  boxplot(data[i,,])
}
```

***PCA**
```{r}
# 
Names = list(rep(c("person1","person2","person3","person4","person5","person6","person7","person8","person9","person10"),10),
             c("coef1","coef2","coef3","coef4","coef5","coef6","coef7","coef8","coef9","coef10"))
data = array(data, dim=c(100,10), dimnames = Names)
pcadata = prcomp(data, center = TRUE, scale. = TRUE)
summary(pcadata)
str(pcadata)
```

```{r}
ggbiplot(pcadata)

```


***KNN***
```{r}
library(class) ##run knn function
ran <- sample(1:nrow(data), 0.9 * nrow(data)) 
std_data <- as.data.frame(scale(data)) 

```
***KNN Algorithm***
```{r}
dim = 100
idx = sample(nrow(data), dim)
targets = as.factor(rep(c(1:10),10))
errors = rep(NA, 100)
for (j in 1:dim) {
  # Labels
  target_ = targets[idx[-j]]
  test_ = targets[idx[j]]
  # Train/test
  train = data[idx[-j],]
  test = data[idx[j],]
  #Predict
  pr <- knn(train,test,cl=target_, k=2)
  
  errors[j] = pr != test_

}
mean(errors)
```


```{r}
#plot(armdata[[2]][[1]][[1]][,1],armdata[[2]][[1]][[1]][,3])
plot_ly(x=armdata[[2]][[1]][[1]][,1],y=armdata[[2]][[1]][[1]][,2],z = armdata[[2]][[1]][[1]][,3],type = "scatter3d", mode = "lines")

```
